siom79/japicmp

- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java
this is done for instance ear , package
in my own project we have set a dedicated packaging for public api 
@siom79  this feature could be merged with the skipPom ( currently not done to avoid breaking changes)
> Add feature to filter analisys based on Maven package

- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpReport.java
- japicmp-testbase/japicmp-test-maven-plugin/pom.xml
- japicmp-testbase/japicmp-test-maven-plugin/src/test/java/japicmp/test/ITReportTitle.java
Change the maven site japicmp report to be more descriptive.  The report name is more consistent with other reports like PMD, Findbugs, and Checkstyle.  The report description includes the old and new versions.
> Change maven site report name and description

- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java
This adds the ability to skip execution on the command line:
```
$ mvn -Djapicmp.skip=true clean verify
```
This is a fairly standard convention followed by other plugins
such as the enforcer plugin, and core plugins like the jar and
source plugins.
> Allow skipping via a property

- japicmp/src/main/java/japicmp/versioning/VersionChange.java
- japicmp/src/test/java/japicmp/versioning/VersionChangeTest.java
> Fix ignoreMissingOldVersion and NewVersion check

- japicmp/src/main/resources/html.xslt
XSLT formatting results in copious amounts of extraneous whitespace (ca 15% in Guava 18 to 19 diff).
> Reduce extraneous whitespace in the generated HTML report

- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java
> Maven artifact can be a directory causing a spurious stack trace in the log

- japicmp/src/main/java/japicmp/model/JApiBehavior.java
I received NPE when doing japicmp and WildFly experiments - https://github.com/rsvoboda/rsvoboda-playground/tree/master/japicmp-and-wildfly#generate-api-diff---custom-branch
I used temporary branch https://github.com/rsvoboda/japicmp/commit/7049ddbbbe10e7a335bece36541f415ace2ed447 to see where the troubles were, this is version without stdout stuff.
Just for the record, problematic stuff is javassist / undertow related:
```
exceptions == null - javassist.bytecode.ExceptionsAttribute@4ba6f55a - methodOptional: javassist.CtConstructor@4fa4e58f[public HttpRequestParser$$generated (Lorg/xnio/OptionMap;)V] - class: io.undertow.server.protocol.http.HttpRequestParser$$generated
exceptions == null - javassist.bytecode.ExceptionsAttribute@72044ee4 - methodOptional: …
```
> extractExceptions changes to prevent NPE

- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java
- japicmp/src/main/java/japicmp/model/JApiAnnotation.java
- japicmp/src/main/java/japicmp/model/JApiAnnotationElement.java
- japicmp/src/main/java/japicmp/model/JApiClass.java
- japicmp/src/main/java/japicmp/model/JApiClassFileFormatVersion.java
- japicmp/src/main/java/japicmp/model/JApiConstructor.java
- japicmp/src/main/java/japicmp/model/JApiField.java
- japicmp/src/main/java/japicmp/model/JApiImplementedInterface.java
- japicmp/src/main/java/japicmp/model/JApiMethod.java
- japicmp/src/main/java/japicmp/model/JApiReturnType.java
- japicmp/src/main/java/japicmp/model/JApiSuperclass.java
- japicmp/src/main/java/japicmp/output/semver/SemverOut.java
o Implemented toString methods for all JApiCompatibility
o japicmp-maven-plugin writes now errors to the console if an incompatible change is detected
> 213: Output of japicmp-maven-plugin improved

- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
- japicmp/src/test/java/japicmp/compat/CompatibilityChangesTest.java
The JLS section on final methods says this:
"Changing an instance method that is not declared final to be declared
final may break compatibility with existing binaries that depend on the
ability to override the method."
If the enclosing class is final, existing binaries have no mechanism to override
the method, so the change does not break compatibility.
This is relevant for Java to Kotlin migrations as the Kotlin compiler adds the
'final' modifier to all methods of final classes, whereas the Java compiler does
exactly what is in source code.
Closes: https://github.com/siom79/japicmp/issues/206
> Teach japicmp about 'effectively final'

- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpReport.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/Parameter.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/PluginParameters.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/SkipModuleStrategy.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/VersionChange.java
- japicmp-maven-plugin/src/test/java/japicmp/maven/JApiCmpMojoTest.java
- japicmp-maven-plugin/src/test/java/japicmp/maven/SkipModuleStrategyTest.java
- japicmp-maven-plugin/src/test/java/japicmp/maven/VersionChangeTest.java
- japicmp-testbase/japicmp-test-maven-plugin-userproperty/pom.xml
- japicmp-testbase/japicmp-test-maven-plugin-userproperty/src/test/java/japicmp/test/ITSkipped.java
- japicmp-testbase/pom.xml
Adds ability to set certain break and skip parameter settings via `<properties>` section in pom OR via command-line, e.g.: `mvn clean verify -Djapicmp.skipXmlReport`
> resolves #240 allowing user properties

- japicmp/src/main/java/japicmp/output/OutputFilter.java
This PR attempts to address #247: if a class has been marked as MODIFIED, it should be part of the final report even if outputOnlyModifications has been set, regardless of whether its nested elements are marked as `MODIFIED'.
The tests run fine with this change. However, I did not find the right place to add a unit test for this.
> [OutputFilter] Do not filter out classes that are MODIFIED from the final report when using 'outputOnlyModifications'

- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
- japicmp/src/test/java/japicmp/compat/CompatibilityChangesTest.java
- pom.xml
Fixes #310.
A compatibility change is reported only when:
* The class is not `final`
* The class is `final` but the constructor was `public`
All the other cases are considered binary/source compatible changes.
> Refine `CONSTRUCTOR_LESS_ACCESSIBLE` evaluation

- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java
Similar to #292, artifacts for `ejb` packaging should resolve to a `jar` extension.
> Fix resolution of artifact to compare for ejb packaging

- japicmp-maven-plugin/pom.xml
- japicmp-testbase/pom.xml
- pom.xml
Changes:
* maven 3.6.0 is buggy, upped to latest 3.6.x (3.6.3)
* aligned resolver version with maven version
* using latest maven-plugin-plugin
* set provided scope for maven bits and resolver bits
* updated dependencies
* parent POM cleanup (upped plugin versions where applicable, added where missing), moved all to pluginMgmt
This results in "lighter" plugin, not only it does not download Maven 2 bits (maven-project???), but also will not re-download maven bits as they are now provided. Making the provided is possible with latest maven-plugin-plugin, that also emits warnings in build if maven bits not set to provided scope.
> Update Maven build and plugin

- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpReport.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/MavenParameters.java
- japicmp-maven-plugin/src/test/java/japicmp/maven/SkipModuleStrategyTest.java
Dropped (unused) deprecated bits to get them out of plugin.
Also, reuse what Maven did for us already (resolved the project),
as Mojo requires compile resolution and that most probably
happened already in verify phase.
As "side effect" fixes https://github.com/siom79/japicmp/issues/327
> Drop Maven legacy (and unused bits) and reuse work done by Maven

- japicmp/src/main/java/japicmp/cmp/JarArchiveComparator.java
- japicmp/src/main/java/japicmp/cmp/ReducibleClassPool.java
- japicmp/src/test/java/japicmp/cmp/ClassesHelper.java
Addresses #318.
Reduce the maximum memory requirement of the `JarArchiveComparator` by having it apply filters while classes are being loaded and removing them from the `ClassPool` when filtered.
If a package filter is encountered we switch to a 2 step procedure, first reading all package filters, then reloading all classes. (Quite annoying but I don't see an alternative apart from rejecting the PR).
Diff is a bit larger than desired so tests like `FilterTest`, that relied on filtering to happen after a `CtClass` is created, continue to work as-is.
> Eagerly filter classes

- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
- japicmp/src/test/java/japicmp/compat/CompatibilityChangesTest.java
Fixes #110
This now uses `METHOD_NOW_THROWS_CHECKED_EXCEPTION` and `METHOD_NO_LONGER_THROWS_CHECKED_EXCEPTION` for constructors as well. Is that acceptable or do they have to be renamed?
> Check constructors for changed checked exceptions

- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
- japicmp/src/main/java/japicmp/model/JApiBehavior.java
- japicmp/src/main/java/japicmp/model/JApiCompatibilityChange.java
- japicmp/src/main/java/japicmp/model/VarargsModifier.java
- japicmp/src/main/java/japicmp/util/ModifierHelper.java
- japicmp/src/test/java/japicmp/compat/CompatibilityChangesTest.java
- src/site/markdown/MavenPlugin.md
Changing a method from varargs to non-varargs is most likely a source incompatible change:
```java
void test(int... args) {
}
// to:
void test(int[] args) {
}
```
Fails with the following source code:
```java
test(1, 2);
```
Changing a method from non-varargs to varargs is most likely source compatible (unless I am overlooking some corner case with overloads).
Feedback is appreciated!
> Detect method varargs changes

- japicmp-testbase/japicmp-test-v1/src/main/java/japicmp/test/DefaultMethod.java
- japicmp-testbase/japicmp-test-v2/src/main/java/japicmp/test/DefaultMethod.java
- japicmp-testbase/japicmp-test/pom.xml
- japicmp-testbase/japicmp-test/src/test/java/japicmp/test/DefaultMethodTest.java
- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
Resolves an issue default methods weren't considered when the method was first declared in another interface higher up in the hierarchy.
We now double-check for all discovered abstract methods whether an implemented interface has a default method for that method. We only accept such a default method if the interface containing it extends the interface with the original definition.
> Check implemented interfaces for default methods of super interface

- japicmp-testbase/japicmp-test-v1/src/main/java/japicmp/test/semver/finalpublicmethod/ClassWithFinalPublicMethodInSuperClass.java
- japicmp-testbase/japicmp-test-v2/src/main/java/japicmp/test/semver/finalpublicmethod/ClassWithFinalPublicMethodInSuperClass.java
- japicmp-testbase/japicmp-test/src/test/java/japicmp/test/FinalMethodTest.java
- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
The plugin currently can detect when a method was moved to a sub class, but it doesn't take all properties into account, including (but not limited to) `final` and access modifiers.
With this PR it can detect if `final` was added when it moved to the super class.
> Detect methods moved to super class with added final

- japicmp/pom.xml
- pom.xml
As far as I can tell this is no longer required/used.
> Remove javax.activation dependency

- pom.xml
It is best practice to "lock down" plugin versions, as otherwise they may become "moving target".
> There are a LOT of warnings that plugin is missing version.

- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpReport.java
- japicmp-maven-plugin/src/main/java/japicmp/maven/MavenParameters.java
- japicmp-maven-plugin/src/test/java/japicmp/maven/SkipModuleStrategyTest.java
Not only it is unused, but starting with Maven 3.9.1 it will cause a WARNING, making plugin look bad.
For details, see here:
https://issues.apache.org/jira/browse/MNG-7706
> Drop unused parameter ${localRepository}.

- japicmp/src/main/java/japicmp/model/JApiAttribute.java
- japicmp/src/main/java/japicmp/model/JApiClassType.java
- japicmp/src/main/java/japicmp/model/JApiModifier.java
- japicmp/src/main/java/japicmp/model/JApiReturnType.java
- japicmp/src/main/java/japicmp/model/JApiType.java
- japicmp/src/main/java/japicmp/output/extapi/jpa/model/JpaName.java
I noticed that several classes have a method `public JApiChangeStatus getChangeStatus()` but were not advertised as `JApiHasChangeStatus` implementors.
> Make classes implement `JApiHasChangeStatus` if they already do

- japicmp-testbase/japicmp-test/src/test/java/japicmp/test/output/SemverOutIntegTest.java
- japicmp/src/main/java/japicmp/output/incompatible/IncompatibleErrorOutput.java
- japicmp/src/main/java/japicmp/output/semver/SemverOut.java
- japicmp/src/test/java/japicmp/output/semver/SemverOutTest.java
According to [Sonar rules](https://rules.sonarsource.com/java/RSPEC-1192/ "String literals should not be duplicated"):
> _Duplicated string literals make the process of refactoring complex and error-prone, as any change would need to be propagated on all occurrences._
The rationale behind this PR is that I'm working on a new output generator for japicmp that would benefit from `SemverOut` results being defined as constants.
> Extract string constants from `SemverOut` so they can be reused

- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
- japicmp/src/main/java/japicmp/model/JApiHasAnnotations.java
- japicmp/src/main/java/japicmp/model/JApiHasGenericTemplates.java
Given that:
1. All current implementations of `JApiHasAnnotations` and `JApiHasGenericTemplates` implement `JApiCompatibility` as well.
2. Code in `CompatibilityChanges` assumes that any such instances can be safely casted to `JApiCompatibility`.
I believe that we can say that, _by definition_, all instances of `JApiHasAnnotations` and `JApiHasGenericTemplates` _must be_ a `JApiCompatibility`.
So I think these two interfaces should extend `JApiCompatibility` to clarify this relationship and to avoid unnecessary type casting.
> Refactor interface hierarchy to avoid unnecessary casting

- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
- japicmp/src/main/java/japicmp/model/JApiClass.java
- japicmp/src/main/java/japicmp/model/JApiSuperclass.java
- japicmp/src/test/java/japicmp/compat/CompatibilityChangesTest.java
I found what I believe is a small bug in the source code which is assigning the wrong `correspondingJApiClass` to a `JApiSuperclass`.
> Correctly set a superclass' corresponding class

- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
- japicmp/src/main/java/japicmp/model/JApiImplementedInterface.java
- japicmp/src/test/java/japicmp/compat/CompatibilityChangesTest.java
Currently, an implemented interface's corresponding class is set only when its change status is `MODIFIED` or `UNCHANGED`. This pull request also initializes it when the implemented interface is `NEW`.
> Initialize the corresponding class of a NEW implemented interface

- japicmp-testbase/japicmp-test-ant-task/pom.xml
- japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java
- japicmp/src/main/java/japicmp/model/JApiAnnotation.java
- japicmp/src/main/java/japicmp/model/JApiCompatibilityChangeType.java
- japicmp/src/test/java/japicmp/compat/CompatibilityChangesTest.java
- japicmp/src/test/java/japicmp/util/CtAnnotationBuilder.java
Resolves:
-  https://github.com/siom79/japicmp/issues/385
Related pull request:
- https://github.com/siom79/japicmp/pull/386
This is an alternative approach, in which changes to annotations will be ignored if option `--no-annotations` is set.
> Optionally take changes to annotations into account

- japicmp/src/test/java/japicmp/compat/CompatibilityChangesTest.java
- japicmp/src/test/java/japicmp/util/CtClassBuilder.java
- japicmp/src/test/java/japicmp/util/CtElement.java
- japicmp/src/test/java/japicmp/util/CtFieldBuilder.java
- japicmp/src/test/java/japicmp/util/CtMethodBuilder.java
I updated test classes `CtClassBuilder`, `CtMethodBuilder` and `CtFieldBuilder` so that tests can create annotations with elements.
Example:
```java
// Creates a test class with an empty annotation:
//     @MyAnnotation
//     class Test { }
CtClassBuilder.create().name("japicmp.Test").withAnnotation("japicmp.MyAnnotation");
// Creates a test class with an annotation that contains one element:
//     @MyAnnotation(foo = 1000)
//     class Test { }
CtClassBuilder.create().name("japicmp.Test").withAnnotation("japicmp.MyAnnotation", new CtElement("foo", 1000));
```
This allows for test scenarios where compatibility change `ANNOTATION_MODIFIED` should be reported.
Closes #385
> Expand test coverage for compatibility changes related to annotations

- japicmp-testbase/japicmp-test-maven-plugin/pom.xml
- japicmp/src/main/java/japicmp/output/incompatible/IncompatibleErrorOutput.java
- japicmp/src/test/java/japicmp/output/incompatible/IncompatibleErrorOutputTest.java
I noticed that the maven plugin does not break on `METHOD_RETURN_TYPE_GENERICS_CHANGED`. 
This looked to be because method is not given a JApiCompatibilityChange, but instead the return type of the method is given a JApiCompatibilityChange. 
https://github.com/siom79/japicmp/blob/68727ed928502f0062cab4177eea6efe21c2e697/japicmp/src/main/java/japicmp/compat/CompatibilityChanges.java#L453 
So added a check for the compatibility changes in the return types of methods.
> fix: check changes in return types

- .github/workflows/ci.yml
- japicmp-testbase/japicmp-test-maven-plugin/pom.xml
- japicmp/pom.xml
- pom.xml
This PR adds the new markdown summary report to the github summary.
The version of the `japicmp-maven-plugin` is hard coded due to cyclic dependencies plugin (we try to generate a report with the current version that is build). Using an additional site-report step did not succeed, because the spotbugs plugin no longer supports in the current version java 1.8 (and the build fails). Skipping the spotbugs plugin in the site-report only for JDK 1.8 did not work.
> Add markdown report to github summary

- japicmp/src/main/java/japicmp/output/markdown/MarkdownTable.java
> Fix NPE on `MarkdownTable.calculateMaxWidth`
